[[redirects]]
  from = "/brightai-platform/static/*"
  to = "/brightai-platform/build/static/:splat"
  status = 200

[[redirects]]
  from = "/brightai-platform/*"
  to = "/brightai-platform/build/:splat"
  status = 200

[[redirects]]
  from = "/brightai-platform/*"
  to = "/brightai-platform/build/index.html"
  status = 200
